# .github/workflows/ci_cd.yml

name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    # A job contains sequence of steps.
    steps:
    # Below line means the assistant will take code from github and give it to runner.
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - uses: iterative/setup-cml@v2
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run main file
      run: |
        python main.py
    
    - name: Run Tests
      run: |
        python -m unittest discover

    - name: Create CML report
      # picking github token from environment beacuse we want that github and assistant will know that 
      # i am doing these things --> they can communicate with each other.
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |

        echo "# First Line of our report" >> report.md
        # writing title on report.md file
        echo "## Bar Plots" >> report.md
        # sending the output from main.py file i.e., Bar Plot to report.md file
        echo '![](./bars.png "Bar plot")' >> report.md
        echo "## Line Plots" >> report.md
        echo '![](./lines.png "Bar plot")' >> report.md
        # after creating report.md file comment output on github project
        cml comment create report.md